version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    versioning-strategy: "lockfile-only"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:00"
      timezone: "Europe/Zagreb"
    rebase-strategy: "disabled"
    ignore:
      - dependency-name: "rails"
    groups:
      all-non-major-dependency-updates:
        patterns:
          - "*"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "rubocop*"
      rubocop-dependencies:
        patterns:
          - "rubocop*"
